# Generated by Django 4.1.4 on 2023-01-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infopage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('currency', models.CharField(max_length=64)),
                ('location', models.CharField(max_length=64)),
            ],
        ),
    ]
