# Generated by Django 4.1.4 on 2022-12-21 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infopage', '0002_city_country_remove_user_city_remove_user_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='home',
            new_name='is_home',
        ),
    ]
