# Generated by Django 4.1.4 on 2023-01-13 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infopage', '0003_rename_currencycodes_currencycode'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxiPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_taxi_cities', to='infopage.city')),
                ('currency_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infopage.currencycode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_taxi_prices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReataurantPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_restaurant_cities', to='infopage.city')),
                ('currency_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infopage.currencycode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_restaurant_prices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
